apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: amundsen
  name: amundsen-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: eks-prod-ingress
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-8b7bffee,subnet-eaec17b3,subnet-823ae0f5
  labels:
    app: amundsen-ingress
spec:
  rules:
    - host: amundsen.little-engine.com
      http:
        paths:
          - backend:
              serviceName: amundsen-prod-web
              servicePort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amundsen
  name: amundsen-prod-web
  namespace: amundsen
spec:
  ports:
    - name: web
      port: 5000
      targetPort: 5000
  selector:
    app: amundsen
    component: frontend
    release: amundsen
  type: NodePort